### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by mimoo** [arielgabizon/plonk#1]
Since you created this, here are some errors I picked up:

![2019-953](https://user-images.githubusercontent.com/1316043/122567531-9e090980-cffd-11eb-989a-d2abffe7dad5.png)

missing comma:

<img width="486" alt="2019-953" src="https://user-images.githubusercontent.com/1316043/122567546-a103fa00-cffd-11eb-87fb-71da9339e7de.png">

![on May 1](https://user-images.githubusercontent.com/1316043/122567555-a3665400-cffd-11eb-825a-c78bfc4b9362.png)

should be \bf{x}_j here:

<img width="811" alt="Enforcing public inputs It is quite convenient and direct to enforce values of public" src="https://user-images.githubusercontent.com/1316043/122567569-a6614480-cffd-11eb-935f-69dc072db61d.png">

<img width="653" alt="Remark 4 4  We intentionally do not define a zero-knowlege property for idealized" src="https://user-images.githubusercontent.com/1316043/122567624-b547f700-cffd-11eb-89ea-dfb264284960.png">

<img width="856" alt="One thing to note is that the (LA) can reduce point checks to range checks, More" src="https://user-images.githubusercontent.com/1316043/122567650-bd079b80-cffd-11eb-8747-df537ccd6436.png">

^ shoud be the inverse no? range checks -> point checks reduction

**Comment by mimoo** [comment]
<img width="480" alt="Screen Shot 2021-06-23 at 12 14 10 PM" src="https://user-images.githubusercontent.com/1316043/123079799-1e01eb80-d3d1-11eb-9da2-b052133b0bd5.png">

I believe that's another one, missing -1

**Comment by mimoo** [comment]
<img width="445" alt="Screen Shot 2021-06-23 at 12 16 57 PM" src="https://user-images.githubusercontent.com/1316043/123080138-789b4780-d3d1-11eb-87b2-4eeec9513819.png">

**Comment by mimoo** [comment]
<img width="514" alt="Screen Shot 2021-06-23 at 12 20 11 PM" src="https://user-images.githubusercontent.com/1316043/123080578-ee071800-d3d1-11eb-86b4-defb0149b86c.png">

I don't think the division by Z_H(x) should occur in the two permutation polynomials at the middle, I think it should divide the two middle polynomials after subtraction.

**Comment by mimoo** [comment]
<img width="659" alt="Screen Shot 2021-06-23 at 3 13 06 PM" src="https://user-images.githubusercontent.com/1316043/123102590-14d14880-d3ea-11eb-9883-f892042d2854.png">

^ I think here the reconstruction of t should use X^n and X^{2n}, not zeta

**Comment by arielgabizon** [comment]
Thanks for these comments! I will work through them -
for one thing:
reduce point checks to range checks is correct.
The idea is that range checks are what is easy/what we already have, when using ranged protocols/proving things by dividing by Z_H; so that's what we need to reduce to.
(That's in the ranged protocol, it is true that ultimately in the "compiled protocol" using KZG all checks are reduced to a point check by randomly sampling a challenge point)

**Comment by arielgabizon** [comment]
> <img alt="Screen Shot 2021-06-23 at 3 13 06 PM" width="659" src="https://user-images.githubusercontent.com/1316043/123102590-14d14880-d3ea-11eb-9883-f892042d2854.png">
> 
> ^ I think here the reconstruction of t should use X^n and X^{2n}, not zeta

I think not, cause we're deriving the value of t using the three partial polys' values
(The point of splitting t into several polys is to only have to work with degree n and not higher)

**Comment by arielgabizon** [comment]
> <img alt="Screen Shot 2021-06-23 at 12 20 11 PM" width="514" src="https://user-images.githubusercontent.com/1316043/123080578-ee071800-d3d1-11eb-86b4-defb0149b86c.png">
> 
> I don't think the division by Z_H(x) should occur in the two permutation polynomials at the middle, I think it should divide the two middle polynomials after subtraction.

I guess that would be equivalent. Not sure what's better typographically

**Comment by arielgabizon** [comment]
> <img alt="Screen Shot 2021-06-23 at 12 14 10 PM" width="480" src="https://user-images.githubusercontent.com/1316043/123079799-1e01eb80-d3d1-11eb-9da2-b052133b0bd5.png">
> 
> I believe that's another one, missing -1

I don't think so, the verifier adds that -1 in step 8

**Comment by mimoo** [comment]
I guess I'm learning about the protocol by submitting false corrections then :P thanks!

**Comment by arielgabizon** [comment]
There were several true corrections :)

**Comment by mimoo** [comment]
> > <img alt="Screen Shot 2021-06-23 at 3 13 06 PM" width="659" src="https://user-images.githubusercontent.com/1316043/123102590-14d14880-d3ea-11eb-9883-f892042d2854.png">
> > ^ I think here the reconstruction of t should use X^n and X^{2n}, not zeta
> 
> I think not, cause we're deriving the value of t using the three partial polys' values
> (The point of splitting t into several polys is to only have to work with degree n and not higher)

Oh right, so if I understand correctly this is using [Maller's optimization](https://hackmd.io/@mimoo/SJY2CpfAO)!

**Comment by arielgabizon** [comment]
Umm you could perhaps call it a special case of that optimization...not sure..
Btw if you look at the recently updated paper t doesn't appear at all in the opening proof polynomial, cause now it's all encorporated in r using Maller's optimizaiton.
In any case, nice writeup on that!

**Comment by mimoo** [comment]
> > <img alt="Screen Shot 2021-06-23 at 12 20 11 PM" width="514" src="https://user-images.githubusercontent.com/1316043/123080578-ee071800-d3d1-11eb-86b4-defb0149b86c.png">
> > I don't think the division by Z_H(x) should occur in the two permutation polynomials at the middle, I think it should divide the two middle polynomials after subtraction.
> 
> I guess that would be equivalent. Not sure what's better typographically

the polynomials are not individually divisible by Z_H no? It's the subtraction that is (otherwise you'd get a result in the rational numbers)

**Comment by mimoo** [comment]
![httpseprint iacr org2019953 pdf](https://user-images.githubusercontent.com/1316043/126760705-04dd0439-ce0e-4113-adf3-480772f49977.png)

btw this is still an error right?

**Comment by mimoo** [comment]
![Screen Shot 2021-07-23 at 11 22 01 AM](https://user-images.githubusercontent.com/1316043/126762561-cd8420db-c98b-46c8-bcbc-2c3771b6f39f.png)
same here, it looks like the permutation stuff is missing from c?

**Comment by mimoo** [comment]
> Umm you could perhaps call it a special case of that optimization...not sure..
> Btw if you look at the recently updated paper t doesn't appear at all in the opening proof polynomial, cause now it's all encorporated in r using Maller's optimizaiton.
> In any case, nice writeup on that!

oh I see! So it's not really a KZG opening anymore! 

You reduced the problem of showing that `f(z) = Z_H(z) t(z)`

to showing that z is a root of `f(x, z) - Z_H(z) t(x)` (thus `f(z, z) = Z_H(z) t(z)`.

EDIT: nevermind, I think we're opening `f(x, z) - Z_H(z)t(x)` at `z`, which is 0

EDIT2: oh I see, so that's where Maller's optimization is used

**Comment by arielgabizon** [comment]
> ![Screen Shot 2021-07-23 at 11 22 01 AM](https://user-images.githubusercontent.com/1316043/126762561-cd8420db-c98b-46c8-bcbc-2c3771b6f39f.png)
> same here, it looks like the permutation stuff is missing from c?

So the idea is to split the terms between r' and r_0.
I think all the terms appear in them together

**Comment by mimoo** [comment]
OK, so I think I finally got it, and I wrote [a note](https://hackmd.io/@mimoo/BkbKGedA_) to explain how we go from "send the evaluations of f(z), t(z) and have the verifier check f(z) = t(z) Z_H(z)" to "send the evaluations and have the verifier check the opening proofs".

The thing that finally clicked for me was that instead of having the verifier check that identity by themselves, we have them check the polynomial (which is where Maller optimization is used).

**Comment by mimoo** [comment]
> > ![Screen Shot 2021-07-23 at 11 22 01 AM](https://user-images.githubusercontent.com/1316043/126762561-cd8420db-c98b-46c8-bcbc-2c3771b6f39f.png)
> > same here, it looks like the permutation stuff is missing from c?
> 
> So the idea is to split the terms between r' and r_0.
> I think all the terms appear in them together

but where is the third permutation poly (S_sigma3) from the original circuit equation?

![Screen Shot 2021-07-23 at 5 23 58 PM](https://user-images.githubusercontent.com/1316043/126804481-4fe38168-5fb1-4592-bbe9-07d91cd55339.png)

**Comment by arielgabizon** [comment]
The factor of the third perm poly is in r', it doesn't need to be made constant like first two, cause r is already linear after fixing those.

**Comment by mimoo** [comment]
I guess I'm confused as to where does the line I pointed out here goes?

![Screen Shot 2021-07-23 at 8 06 59 PM](https://user-images.githubusercontent.com/1316043/126823408-04fda899-cb3f-4d67-8c20-7d04a31be84e.png)

(I wrote this, to try to find out how this was transformed in the PLONK paper)

**Comment by mimoo** [comment]
nevermind, I figured it out :D I should write a note somewhere. I guess the optimization with r_0 through me off a bit.

**Comment by mimoo** [comment]
<img width="107" alt="Screen Shot 2021-08-10 at 10 14 21 AM" src="https://user-images.githubusercontent.com/1316043/129063218-0bd1f6c2-ca6e-4c6a-962d-2833676a6a23.png">

is this one a typo too? I've been trying to understand where that formula comes from for lagrange basis
